### ISSUE TITLE
bin/run.rb never finds the raid dir

### ISSUE THREAD

**Issue by bhush9** [apachelogger/kde-os-autoinst#2]
https://github.com/apachelogger/kde-os-autoinst/blob/e64885cb063b60e9fc2a453d4c051316959e9df3/bin/run.rb#L95

```
bin/run.rb:95:in `realpath': No such file or directory @ realpath_rec - /workspace/raid (Errno::ENOENT)                                                                                                                                        
        from bin/run.rb:95:in `<main>'
```

**Comment by bhush9** [comment]
I am not sure what I am doing wrong.. I think I figured that at least I've to copy/move `wok/raid` to `/workspace/raid` before running other tests? right? but that results in other tests failing at this

![last](https://user-images.githubusercontent.com/1061944/34565347-8506e7ea-f180-11e7-9b1e-94ebb566f0f7.png)

Which I find bit weird tbh...

**Comment by bhush9** [comment]
`qemu-image info` for both of wok/raid/1 and raid/1 for reference

```
root@584919159c49:/workspace# qemu-img info raid/l1 
image: raid/l1
file format: qcow2
virtual size: 20G (21474836480 bytes)
disk size: 7.0G
cluster_size: 65536
Snapshot list:
ID        TAG                 VM SIZE                DATE       VM CLOCK
1         lastgood               1.9G 2018-01-04 13:23:01   00:08:36.375
Format specific information:
    compat: 1.1
    lazy refcounts: false
    refcount bits: 16
    corrupt: false
root@584919159c49:/workspace# qemu-img info wok/raid/l1 
image: wok/raid/l1
file format: qcow2
virtual size: 10G (10737418240 bytes)
disk size: 708K
cluster_size: 65536
backing file: /workspace/raid/1
Format specific information:
    compat: 1.1
    lazy refcounts: false
    refcount bits: 16
    corrupt: false
```

**Comment by bhush9** [comment]
Ah now that I read it I see what's up.. Fix incoming.
